<a href="https://colab.research.google.com/github/NicolyAvelino/algebraLinear/blob/main/Aula2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 2 - Matrizes

## Matrizes - Simples

Nesta parte, vamos usar a estrutura simples de listas para trabalhar com matrizes. Depois veremos que podemos usar uma biblioteca para trabalhar de forma mais apropriada com matrizes

Podemos pensar em uma lista como um vetor unidimensional. Parecido com o $\mathbb{R}^n$ que estudamos em aula

In [ ]:
a = [1, 3,5,-2,5]
a

[1, 3, 5, -2, 5]

In [ ]:
type(a)

list

In [ ]:
# Primeiro elemento de a
a[0]

1

In [ ]:
# Último elemento de a
a[4]

5

Exercício: Efetue a soma do segundo elemento de a e o quarto elemento.

In [9]:
a = [1, 3,5,-2,5]

x = a[1] + a[3]
print(x)

1


In [ ]:
# Tamanho da lista
len(a)

5

In [ ]:
# Exemplo: Soma de vetores
# Considere
a = [2,6,7]
b = [4,5,6]

# Definimos o vetor soma, primeiramente como uma lista vazia
c = []
# e vamos adicionando os respectivos elementos:
i = 0
while(i<len(a)):
  c.append(a[i]+b[i])
  i = i+1

In [ ]:
c

[6, 11, 13]

Exercício: Multiplicação por escalar.
- Solicite ao usuário que digite o valor de n (o tamanho do vetor)
- Solicite ao usuário que digite os valores do vetor
- Solicite ao usuário o valor do escalar.
- Imprima o vetor resultante

In [26]:
tamanhoVet = int(input('declare o tamanho que deseja para o vetor: '))

# vetA = [1, 2, 3]
vetA = []
i = 0
while(i< tamanhoVet):
  vetA.append(int(input('declare o valor: ')))
  i = i+1

valorEsc = int(input("declare o valor escalar: "))
i = 0
while(i<len(vetA)):
  vetA[i]= vetA[i] * valorEsc 
  i = i+1
print(vetA)  


declare o tamanho que deseja para o vetor: 3
declare o valor: 1
declare o valor: 2
declare o valor: 3
declare o valor escalar: 2
[2, 4, 6]


In [ ]:
# Matrizes
# Podemos pensar em uma matriz como uma lista de listas. Por exemplo

In [ ]:
A = [[2,3,4],
     [3,-1,0]]

In [ ]:
A

[[2, 3, 4], [3, -1, 0]]

# Matrizes - Numpy

## Bibliotecas.

No Python, existem milhares de bibliotecas (que são scripts) que auxiliam no desenvolvimento de códigos. Vamos trabalhar agora com a biblioteca numpy, 
que funciona como um espécie de calculadora.

In [ ]:
import numpy as np
# import   - Padrão para a importação de bibliotecas.
# numpy    - Nome da biblioteca que estamos importando.
# as np    - Apelido ou abreviação que damos a biblioteca, para não ter que escrever numpy. Assim, podemos usar a abreviação np

In [ ]:
# Parecido com as listas, mas com maiores recursos, temos as arrays.
# Exemplo:

a = np.array([2, 4,5])

In [ ]:
a

array([2, 4, 5])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
# Podemos definir arrays bidimensionais
A = np.array([
    [1,2,4],
    [3,4,5]
])

In [ ]:
A

array([[1, 2, 4],
       [3, 4, 5]])

In [ ]:
# Dimensão do array
A.shape

(2, 3)

In [ ]:
# Considerando uma célula em específico. Ex Cédula na segunda linha e terceira coluna
A[1,2]


5

In [ ]:
# Criando uma matriz com dada dimensão, mas vazia: Ex matriz de ordem 2x3
B = np.empty(shape=(2,3))

In [ ]:
B

array([[2., 0., 0.],
       [0., 0., 0.]])

Exercício: Considere duas matrizes A e B e um número real $\lambda$

Soma

- Verificar se possuem a mesma dimensão
- Em caso afirmativo, realize a soma dessas matrizes

Multiplicação por escalar

- Realizar a multiplicação do escalar e a matriz

In [ ]:
# Pode considerar como exemplo as matrizes A e B abaixo e o número real c

In [ ]:
A = np.array([[2,-4,5,4],
              [3,0,1,5],
              [0,-1,0.4,4]])
A

array([[ 2. , -4. ,  5. ,  4. ],
       [ 3. ,  0. ,  1. ,  5. ],
       [ 0. , -1. ,  0.4,  4. ]])

In [ ]:
B = np.array([[1,1,5.2,4],
              [1,1,1,2],
              [2,-1.5,2,2]])
B

array([[ 1. ,  1. ,  5.2,  4. ],
       [ 1. ,  1. ,  1. ,  2. ],
       [ 2. , -1.5,  2. ,  2. ]])

In [ ]:
c = 3.5

In [36]:
import numpy as np

A = np.array([[2,-4,5,4],
              [3,0,1,5],
              [0,-1,0.4,4]])

B = np.array([[1,1,5.2,4],
              [1,1,1,2],
              [2,-1.5,2,2]])

if A.shape == B.shape:
  print('mesma dimencao')
  C = np.empty(shape=(3,4))

  linhas = A.shape[0]
  colunas = A.shape[1]

  i =0
  j = 0
  while(i<linhas):
    while(j<colunas):
      C[i,j] = A[i,j]+ B[i,j] 
      j = j + 1
    i = i + 1
  print(C)

  print("")

  linhas = A.shape[0]
  colunas = A.shape[1]

  i =0
  j = 0
  while(i<linhas):
    while(j<colunas):
      C[i,j] = C[i,j] * 3.5
      j = j + 1
    i = i + 1
  print(C)



  # for i in range(linhas):
  #   for j in range(colunas):
  #       C[i,j] = A[i,j]+ B[i,j] 
  # print(C)

else:
  print('diferentes dimencao')  


# C[0,0] = A[0,0] + B[0,0]





mesma dimencao
[[ 3.  -3.  10.2  8. ]
 [ 3.   0.   1.   5. ]
 [ 0.  -1.   0.4  4. ]]

[[ 10.5 -10.5  35.7  28. ]
 [  3.    0.    1.    5. ]
 [  0.   -1.    0.4   4. ]]


## Funções (ou métodos) no Python.

Muitas vezes, queremos usar um mesmo trecho de código repetidas vezes, trocando apenas os valores das variáveis. Por exemplo, gostariamos de somar outras matrizes, diferentes do exemplo acima. Para isso, poderíamos compilar novamente a parte do código acima, com valores diferentes das matrizes A e B.

No entanto, podemos utilizar funções.

Exemplo de função no Python:

In [ ]:
def soma_1(a):
  c = a+ 1
  return c

In [ ]:
soma_1(10)

11

Exercícios:
- Crie uma função que realiza a soma de duas matrizes
- Crie uma função que realiza a multiplicação de um escalar por uma matriz

In [ ]:
A = np.array([[2,-4,5,4],
              [3,0,1,5],
              [0,-1,0.4,4]])

B = np.array([[1,1,5.2,4],
              [1,1,1,2],
              [2,-1.5,2,2]])

if A.shape == B.shape:
  print('mesma dimencao')
  C = np.empty(shape=(3,4))

  linhas = A.shape[0]
  colunas = A.shape[1]

  i =0
  j = 0
  while(i<linhas):
    while(j<colunas):
      C[i,j] = A[i,j]+ B[i,j] 
      j = j + 1
    i = i + 1
  print(C)

  print("")

  linhas = A.shape[0]
  colunas = A.shape[1]

  i =0
  j = 0
  while(i<linhas):
    while(j<colunas):
      C[i,j] = C[i,j] * 3.5
      j = j + 1
    i = i + 1
  print(C)



  # for i in range(linhas):
  #   for j in range(colunas):
  #       C[i,j] = A[i,j]+ B[i,j] 
  # print(C)

else:
  print('diferentes dimencao')  

## Outras operações com matrizes

### Determinante.

Dada uma matriz  
$$A = 
\begin{pmatrix}
a_{1,1} & a_{1,2}\\
a_{2,1} & a_{2,2}
\end{pmatrix}$$
Definimos o determinante de $A$ por
$$det(A) = a_{1,1}a_{2,2}- a_{1,2}a_{2,1}$$

Exercício: 
- Crie uma função que calcula o determinante de uma matriz 2x2
- Crie uma função que calcula o determinante de uma matriz 3x3
$$A = 
\begin{pmatrix}
a_{1,1} & a_{1,2} & a_{1,2}\\
a_{2,1} & a_{2,2} & a_{2,3}\\
a_{3,1} & a_{3,2} & a_{3,3}\\
\end{pmatrix}$$
Definimos o determinante de $A$ por
$$det(A) = a_{1,1}a_{2,2}a_{3,3} + a_{1,2}a_{2,3}a_{3,1} + a_{1,2}a_{2,1}a_{3,2}- a_{1,2}a_{2,2}a_{3,1} - a_{3,2}a_{2,3}a_{1,1} - a_{3,3}a_{2,1}a_{1,2}$$

## Multiplicação de Matrizes

Dados duas matrizes $A = (a_{i,j})$ de dimensão $n\times p$ e $B = (b_{i,j})$ de dimensão $p\times m$, o produto de $A$ por $B$ é a matriz $C = (c_{i,j})$ de dimensão $n\times m$ tal que
$$c_{i,j} = \sum_{k=1}^p a_{i,k}b_{k, j}$$

Exercício: Construa uma função que recebe duas matrizes $A$ e $B$ e retorna o produto $A\times B$.